# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-24.04"

  tools:
    python: "mambaforge-22.9"

# compile documentation using a conda environment (try to solve mysqlclient
# dependency issue)
conda:
  environment: django-data/image/docs/environment.yml

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: django-data/image/docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all
