
# a variant of db image using postgresql Database
db:
  # get the latest postgres server
  image: postgres:9.6

  # Set db environment
  environment:
    POSTGRES_PASSWORD: ***REMOVED***

  # to export volume, as recommeded in https://registry.hub.docker.com/u/library/mysql/
  volumes:
    - "./postgres-data:/var/lib/postgresql/data"
    - "/etc/localtime:/etc/localtime:ro"

  ports:
    - "35432:5432"


uwsgi:
  # a custom image for django
  build: ./uwsgi

  # exec a different command from image
  command: uwsgi --ini /var/uwsgi/image_uwsgi.ini

  # set working dir for uwsgi
  working_dir: /var/uwsgi/image/

  # define volumes
  volumes:
    - "./django-data/:/var/uwsgi/"
    - "/etc/localtime:/etc/localtime:ro"

  # Expose the default port

  # link container to database
  links:
    - db


nginx:
  # a custom image for NGINX
  build: ./nginx

  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "./nginx/conf.d/:/etc/nginx/conf.d/"

  # get volumes from uwsgi
  volumes_from:
    - uwsgi

  ports:
    - "65080:80"

  # link container uwsgi
  links:
    - uwsgi
