# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='ManagedTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'managed team',
                'verbose_name_plural': 'managed teams',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='team',
            field=models.ForeignKey(help_text='Your Biosample Team', on_delete=django.db.models.deletion.CASCADE, to='biosample.ManagedTeam'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biosample_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
