# Generated by Django 2.2.7 on 2019-11-13 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uid', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'managed team',
                'verbose_name_plural': 'managed teams',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usi_submission_name', models.CharField(blank=True, db_index=True, help_text='USI submission name', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Waiting'), (1, 'Loaded'), (2, 'Submitted'), (3, 'Error'), (4, 'Need Revision'), (5, 'Ready'), (6, 'Completed')], default=0, help_text='example: Waiting')),
                ('uid_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usi_submissions', to='uid.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'uid'), ('model', 'animal')), models.Q(('app_label', 'uid'), ('model', 'sample')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_data', to='biosample.Submission')),
            ],
            options={
                'verbose_name': 'submission data',
                'verbose_name_plural': 'submission data',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('team', models.ForeignKey(help_text='Your AAP Team', on_delete=django.db.models.deletion.CASCADE, to='biosample.ManagedTeam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biosample_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
