# Generated by Django 2.2.9 on 2020-01-24 16:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='samples_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='samples_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
