# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biosample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='team',
            field=models.ForeignKey(help_text='Your AAP Team', on_delete=django.db.models.deletion.CASCADE, to='biosample.ManagedTeam'),
        ),
    ]
