# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-16 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0026_auto_20190705_1434'),
        ('biosample', '0002_auto_20190416_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usi_submission_id', models.CharField(blank=True, db_index=True, help_text='USI submission id', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Waiting'), (1, 'Loaded'), (2, 'Submitted'), (3, 'Error'), (4, 'Need Revision'), (5, 'Ready'), (6, 'Completed')], default=0, help_text='example: Waiting')),
                ('uid_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usi_submissions', to='image_app.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Loaded'), (2, 'Submitted'), (4, 'Need Revision'), (5, 'Ready'), (6, 'Completed')], default=1, help_text='example: Submitted')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_app.Name')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_data', to='biosample.Submission')),
            ],
            options={
                'verbose_name': 'submission data',
                'verbose_name_plural': 'submission data',
            },
        ),
    ]
