# Generated by Django 2.2.9 on 2020-01-27 15:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biosample', '0003_orphansample'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usi_submission_name', models.CharField(blank=True, db_index=True, help_text='USI submission name', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Waiting'), (1, 'Loaded'), (2, 'Submitted'), (3, 'Error'), (4, 'Need Revision'), (5, 'Ready'), (6, 'Completed')], default=0, help_text='example: Waiting')),
                ('samples_count', models.PositiveIntegerField(default=0)),
                ('samples_status', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orphansample',
            name='team',
            field=models.ForeignKey(default=1, help_text='Your AAP Team', on_delete=django.db.models.deletion.CASCADE, to='biosample.ManagedTeam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orphansample',
            name='submission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_data', to='biosample.OrphanSubmission'),
        ),
    ]
