# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-16 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('biosample', '0003_submission_submissiondata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissiondata',
            name='name',
        ),
        migrations.AddField(
            model_name='submissiondata',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissiondata',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
