# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosample', '0004_auto_20190716_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='usi_submission_id',
        ),
        migrations.RemoveField(
            model_name='submissiondata',
            name='status',
        ),
        migrations.AddField(
            model_name='submission',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='usi_submission_name',
            field=models.CharField(blank=True, db_index=True, help_text='USI submission name', max_length=255, null=True, unique=True),
        ),
    ]
