# Generated by Django 2.2.10 on 2020-05-29 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biosample', '0005_orphansample_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphansample',
            name='submission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submission_data', to='biosample.OrphanSubmission'),
        ),
    ]
