# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-30 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0004_supervisedregistrationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRegistrationProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('registration.registrationprofile',),
        ),
    ]
