# Generated by Django 2.2.7 on 2019-11-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0004_supervisedregistrationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRegistrationProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('registration.registrationprofile',),
        ),
    ]
