# Generated by Django 2.2.7 on 2019-11-13 11:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uid', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_count', models.PositiveIntegerField(default=0, help_text='number of all samples or animals in a submission')),
                ('validation_known_count', models.PositiveIntegerField(default=0)),
                ('issues_count', models.PositiveIntegerField(default=0, help_text='number of samples or animals with issues in validation')),
                ('pass_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(blank=True, max_length=6, null=True)),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=255), default=list, size=None)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uid.Submission')),
            ],
            options={
                'verbose_name_plural': 'validation summaries',
                'unique_together': {('submission', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=255, null=True)),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=255), blank=True, default=list, size=None)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'uid'), ('model', 'animal')), models.Q(('app_label', 'uid'), ('model', 'sample')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uid.Submission')),
            ],
            options={
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
