# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, null=True)),
                ('data', models.BinaryField(null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='image_app.Name')),
            ],
        ),
    ]
