# Generated by Django 2.2.10 on 2020-02-25 15:51

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validationsummary',
            old_name='messages',
            new_name='old_messages',
        ),
        migrations.AddField(
            model_name='validationsummary',
            name='new_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), default=list, size=None),
        ),
    ]
