# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 10:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_auto_20190130_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationresult',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=255), default=list, size=None),
        ),
    ]
