# Generated by Django 2.2.7 on 2019-11-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_auto_20191030_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationresult',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'uid'), ('model', 'animal')), models.Q(('app_label', 'uid'), ('model', 'sample')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
