# Generated by Django 2.2.10 on 2020-02-25 15:51

import ast

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version

    ValidationSummary = apps.get_model(
        "validation",
        "ValidationSummary")

    db_alias = schema_editor.connection.alias

    # Update validation summary
    for summary in ValidationSummary.objects.using(db_alias):
        new_messages = []

        for message in summary.old_messages:
            data = ast.literal_eval(message)
            new_messages.append(data)

        # now update new_messages column
        summary.new_messages = new_messages
        summary.save()


def reverse_func(apps, schema_editor):
    ValidationSummary = apps.get_model(
        "validation",
        "ValidationSummary")

    db_alias = schema_editor.connection.alias

    # Update validation summary
    for summary in ValidationSummary.objects.using(db_alias):
        old_messages = []

        for message in summary.new_messages:
            old_messages.append(message)

        # now update old_messages column
        summary.old_messages = old_messages
        summary.save()


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_auto_20200225_1651'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
