# Generated by Django 2.2.10 on 2020-02-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_auto_20200225_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validationsummary',
            old_name='new_messages',
            new_name='messages',
        ),
        migrations.RemoveField(
            model_name='validationsummary',
            name='old_messages',
        ),
    ]
