# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0004_validationsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationsummary',
            name='issues_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
