# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0005_validationsummary_issues_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationsummary',
            name='validation_known_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
