# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0006_validationsummary_validation_known_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationsummary',
            name='all_count',
            field=models.PositiveIntegerField(default=0, help_text='number of all samples or animals in a submission'),
        ),
        migrations.AlterField(
            model_name='validationsummary',
            name='issues_count',
            field=models.PositiveIntegerField(default=0, help_text='number of samples or animals with issues in validation'),
        ),
    ]
