# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0007_auto_20190620_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationsummary',
            name='json_count',
        ),
    ]
