# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-24 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0029_auto_20191008_1734'),
        ('validation', '0008_remove_validationsummary_json_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validationsummary',
            options={'verbose_name_plural': 'validation summaries'},
        ),
        migrations.AlterUniqueTogether(
            name='validationsummary',
            unique_together=set([('submission', 'type')]),
        ),
    ]
