# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='This website uses cookies to ensure you get the best experience on our website.')),
                ('button_text', models.CharField(default='Got it!', max_length=255)),
                ('cookie_policy_link', models.CharField(max_length=255)),
                ('cookie_policy_link_text', models.CharField(default='Learn more', max_length=255)),
                ('banner_colour', models.CharField(default='#252e39', max_length=255)),
                ('banner_text_colour', models.CharField(default='#ffffff', max_length=255)),
                ('button_colour', models.CharField(default='#3acdf6', max_length=255)),
                ('button_text_colour', models.CharField(default='#ffffff', max_length=255)),
            ],
        ),
    ]
