# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 10:52
from __future__ import unicode_literals

from django.db import migrations


cookie_policy_link = "/image/privacy/"


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    fields = {
        "message": ("This website uses cookies to ensure you get the best "
                    "experience on our website."),
        "button_text": "Got it!",
        "cookie_policy_link": cookie_policy_link,
        "cookie_policy_link_text": "Learn more",
        "banner_colour": "#2FA4E7",
        "banner_text_colour": "#ffffff",
        "button_colour": "#73A839",
        "button_text_colour": "#ffffff"
    }

    CookieConsentSettings = apps.get_model(
        "django_simple_cookie_consent",
        "CookieConsentSettings")

    db_alias = schema_editor.connection.alias
    CookieConsentSettings.objects.using(db_alias).bulk_create([
        CookieConsentSettings(**fields),
    ])


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    fields = {
        "message": ("This website uses cookies to ensure you get the best "
                    "experience on our website."),
        "button_text": "Got it!",
        "cookie_policy_link": cookie_policy_link,
        "cookie_policy_link_text": "Learn more",
        "banner_colour": "#2FA4E7",
        "banner_text_colour": "#ffffff",
        "button_colour": "#73A839",
        "button_text_colour": "#ffffff"
    }

    CookieConsentSettings = apps.get_model(
        "django_simple_cookie_consent",
        "CookieConsentSettings")

    db_alias = schema_editor.connection.alias

    CookieConsentSettings.objects.using(db_alias).filter(**fields).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_cookie_consent', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
