# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-07 15:38
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version

    CookieConsentSettings = apps.get_model(
        "django_simple_cookie_consent",
        "CookieConsentSettings")

    db_alias = schema_editor.connection.alias

    # update the banner privacy link
    CookieConsentSettings.objects.using(db_alias).update(
        cookie_policy_link="/privacy/")


def reverse_func(apps, schema_editor):

    CookieConsentSettings = apps.get_model(
        "django_simple_cookie_consent",
        "CookieConsentSettings")

    db_alias = schema_editor.connection.alias

    # restore the old banner privacy link
    CookieConsentSettings.objects.using(db_alias).update(
        cookie_policy_link="/image/privacy/")


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_cookie_consent', '0003_auto_20191003_1007'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
