# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-30 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecieSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('dictspecie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uid.DictSpecie')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uid.DictCountry')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='speciesynonym',
            unique_together=set([('dictspecie', 'language', 'word')]),
        ),
    ]
