# Generated by Django 2.2.7 on 2019-11-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecieSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('dictspecie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uid.DictSpecie')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uid.DictCountry')),
            ],
            options={
                'unique_together': {('dictspecie', 'language', 'word')},
            },
        ),
    ]
