# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_organization_roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Organization role',
                'verbose_name_plural': 'Organization roles',
                'db_table': 'dict_organization_roles',
            },
        ),
    ]
