# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import image_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictStage',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('label', models.CharField(
                    help_text='Example: submitter', max_length=255)),
                ('term', models.CharField(
                    help_text='Example: EFO_0001741',
                    max_length=255,
                    null=True)),
            ],
            options={
                'verbose_name': 'developmental stage',
            },
            bases=(image_app.models.BaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DictUberon',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('label', models.CharField(
                    help_text='Example: submitter', max_length=255)),
                ('term', models.CharField(
                    help_text='Example: EFO_0001741',
                    max_length=255,
                    null=True)),
            ],
            options={
                'verbose_name': 'organism part',
            },
            bases=(image_app.models.BaseMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='sample',
            name='developmental_stage_term',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='organism_part_term',
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='image_app.DictSex'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='developmental_stage',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='image_app.DictStage'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='organism_part',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='image_app.DictUberon'),
        ),
        migrations.AlterUniqueTogether(
            name='dictsex',
            unique_together=set([('label', 'term')]),
        ),
        migrations.AlterUniqueTogether(
            name='dictuberon',
            unique_together=set([('label', 'term')]),
        ),
        migrations.AlterUniqueTogether(
            name='dictstage',
            unique_together=set([('label', 'term')]),
        ),
    ]
