# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_auto_20190201_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictstage',
            name='confidence',
            field=models.SmallIntegerField(
                choices=[
                    (0,
                     'High'),
                    (1,
                     'Good'),
                    (2,
                     'Medium'),
                    (3,
                     'Low'),
                    (4,
                     'Manually Curated')],
                help_text='example: Manually Curated',
                null=True),
        ),
        migrations.AddField(
            model_name='dictuberon',
            name='confidence',
            field=models.SmallIntegerField(
                choices=[
                    (0,
                     'High'),
                    (1,
                     'Good'),
                    (2,
                     'Medium'),
                    (3,
                     'Low'),
                    (4,
                     'Manually Curated')],
                help_text='example: Manually Curated',
                null=True),
        ),
    ]
