# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_auto_20190201_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='image_app.Submission'),
        ),
    ]
