# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_auto_20190204_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='submission',
        ),
        migrations.AddField(
            model_name='name',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_set', to='image_app.Publication'),
        ),
    ]
