# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0007_auto_20190204_1731'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dictbreed',
            unique_together=set([('supplied_breed', 'specie', 'country')]),
        ),
    ]
