# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0008_auto_20190205_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='material',
            field=models.CharField(default='Organism', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='material',
            field=models.CharField(default='Specimen from Organism', editable=False, max_length=255),
        ),
    ]
