# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_app', '0011_auto_20190218_1518'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('gene_bank_name', 'gene_bank_country', 'datasource_type', 'datasource_version', 'owner')]),
        ),
    ]
