# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0012_auto_20190220_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='animal_age_at_collection_units',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'minutes'), (1, 'hours'), (2, 'days'), (3, 'weeks'), (4, 'months'), (5, 'years')], default=5, help_text='example: years', null=True),
        ),
    ]
