# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0014_auto_20190225_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='datasource_type',
            field=models.SmallIntegerField(choices=[(0, 'CryoWeb'), (1, 'Template'), (2, 'CRB-Anim')], help_text='example: CryoWeb', verbose_name='Data source type'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='datasource_version',
            field=models.CharField(help_text='examples: "2018-04-27", "version 1.5"', max_length=255, verbose_name='Data source version'),
        ),
    ]
