# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('image_app', '0016_auto_20190326_1238'), ('image_app', '0017_auto_20190326_1246')]

    dependencies = [
        ('image_app', '0015_auto_20190312_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name', 'country']},
        ),
        migrations.AlterModelOptions(
            name='dictcountry',
            options={'ordering': ['label'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
    ]
