# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0015_auto_20190312_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name', 'country']},
        ),
    ]
