# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0016_auto_20190326_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictcountry',
            options={'ordering': ['label'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
    ]
