# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0016_auto_20190326_1238_squashed_0017_auto_20190326_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
