# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0017_animal_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(blank=True, help_text='example: 2019-04-01', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='collection_date',
            field=models.DateField(blank=True, help_text='example: 2019-04-01', null=True),
        ),
    ]
