# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0019_submission_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_set', to='image_app.Publication'),
        ),
    ]
