# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0021_validationsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationsummary',
            name='submission',
        ),
        migrations.DeleteModel(
            name='ValidationSummary',
        ),
    ]
