# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0022_auto_20190614_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='storage_new',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'ambient temperature'), (1, 'cut slide'), (2, 'frozen, -80 degrees Celsius freezer'), (3, 'frozen, -20 degrees Celsius freezer'), (4, 'frozen, liquid nitrogen'), (5, 'frozen, vapor phase'), (6, 'paraffin block'), (7, 'RNAlater, frozen -20 degrees Celsius'), (8, 'TRIzol, frozen'), (9, 'paraffin block at ambient temperatures (+15 to +30 degrees Celsius)'), (10, 'freeze dried')], help_text='How the sample was stored', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='storage_processing_new',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'cryopreservation in liquid nitrogen (dead tissue)'), (1, 'cryopreservation in dry ice (dead tissue)'), (2, 'cryopreservation of live cells in liquid nitrogen'), (3, 'cryopreservation, other'), (4, 'formalin fixed, unbuffered'), (5, 'formalin fixed, buffered'), (6, 'formalin fixed and paraffin embedded'), (7, 'freeze dried (vaiable for reproduction)'), (8, 'freeze dried')], help_text='How the sample was prepared for storage', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='availability',
            field=models.CharField(blank=True, help_text='Either a link to a web page giving information on who to contact or an e-mail address to contact about availability. If neither available, please use the value no longer available', max_length=255, null=True),
        ),
    ]
