# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 11:23
from __future__ import unicode_literals

from django.db import migrations

from common.constants import SAMPLE_STORAGE, SAMPLE_STORAGE_PROCESSING


def convert_storage(apps, schema_editor):
    """read from storage field and set data to storage_new"""

    Sample = apps.get_model('image_app', 'Sample')

    for sample in Sample.objects.all():
        if sample.storage is None:
            continue

        sample.storage_new = SAMPLE_STORAGE.get_value_by_desc(sample.storage)
        sample.save()


def convert_storage_processing(apps, schema_editor):
    """
    read from storage_processing field and set data to storage_processing_new
    """

    Sample = apps.get_model('image_app', 'Sample')

    for sample in Sample.objects.all():
        if sample.storage_processing is None:
            continue

        sample.storage_processing_new = \
            SAMPLE_STORAGE_PROCESSING.get_value_by_desc(
                sample.storage_processing)
        sample.save()


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0023_auto_20190701_1317'),
    ]

    operations = [
        migrations.RunPython(convert_storage),
        migrations.RunPython(convert_storage_processing),
    ]
