# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0024_auto_20190701_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='storage_processing',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='storage_new',
            new_name='storage',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='storage_processing_new',
            new_name='storage_processing',
        ),
    ]
