# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0026_auto_20190705_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='biosample_submission_id',
        ),
    ]
