# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0027_remove_submission_biosample_submission_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictbreed',
            options={'verbose_name': 'breed'},
        ),
        migrations.RenameField(
            model_name='dictbreed',
            old_name='mapped_breed',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='dictbreed',
            old_name='mapped_breed_term',
            new_name='term',
        ),
    ]
