# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0027_remove_submission_biosample_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='storage',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'ambient temperature'), (1, 'cut slide'), (2, 'frozen, -80 degrees Celsius freezer'), (3, 'frozen, -20 degrees Celsius freezer'), (4, 'frozen, liquid nitrogen'), (5, 'frozen, vapor phase'), (6, 'paraffin block'), (7, 'RNAlater, frozen -20 degrees Celsius'), (8, 'TRIzol, frozen'), (9, 'paraffin block at ambient temperatures (+15 to +30 degrees Celsius)'), (10, 'freeze dried'), (11, 'frozen, -40 degrees Celsius freezer')], help_text='How the sample was stored', null=True),
        ),
    ]
