# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0028_auto_20190927_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictbreed',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='mapped breed'),
        ),
        migrations.AlterField(
            model_name='dictbreed',
            name='term',
            field=models.CharField(help_text='Example: LBO_0000347', max_length=255, null=True, verbose_name='mapped breed term'),
        ),
    ]
