# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-28 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0029_auto_20191008_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='same_as',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
