# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-29 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0029_auto_20191008_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictspecie',
            name='general_breed_label',
            field=models.CharField(blank=True, help_text='Example: cattle breed', max_length=255, null=True, verbose_name='general breed label'),
        ),
        migrations.AddField(
            model_name='dictspecie',
            name='general_breed_term',
            field=models.CharField(help_text='Example: LBO_0000001', max_length=255, null=True, verbose_name='general breed term'),
        ),
    ]
