# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-29 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0030_auto_20191029_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictspecie',
            name='general_breed_term',
            field=models.CharField(blank=True, help_text='Example: LBO_0000001', max_length=255, null=True, verbose_name='general breed term'),
        ),
    ]
