# Generated by Django 2.2.7 on 2019-11-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='same_as',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='same_as',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
