# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-30 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='biosample_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='animal_set', to='uid.Submission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='biosample_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sample_set', to='uid.Submission'),
            preserve_default=False,
        ),
    ]
