# Generated by Django 2.2.9 on 2020-01-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='alternative_id',
            field=models.CharField(default='fixme', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.PROTECT,
                to='uid.DictSex'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='alternative_id',
            field=models.CharField(default='fixme', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='organism_part',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to='uid.DictUberon'),
            preserve_default=False,
        ),
    ]
