# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-30 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uid', '0002_auto_20191030_1348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together=set([('name', 'breed', 'owner')]),
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together=set([('name', 'animal', 'owner')]),
        ),
    ]
