# Generated by Django 2.2.9 on 2020-01-29 15:30

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version

    Animal = apps.get_model(
        "uid",
        "Animal")

    Sample = apps.get_model(
        "uid",
        "Sample")

    db_alias = schema_editor.connection.alias

    # Update animal and sample
    for animal in Animal.objects.using(db_alias).filter(
            alternative_id="fixme"):
        animal.alternative_id = animal.name
        animal.save()

    for sample in Sample.objects.using(db_alias).filter(
            alternative_id="fixme"):
        sample.alternative_id = sample.name
        sample.save()


def reverse_func(apps, schema_editor):
    """No reverse, cause I can't revert this fields for my animal/samples"""

    pass


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0002_auto_20200129_1623'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
