# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0003_auto_20191030_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='same_as',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='same_as',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
